### ISSUE TITLE
Cannot get to work on Meteor v1.0.4

### ISSUE THREAD

**Issue by PiJoules** [awwx/meteor-mongo-counter#3]
Before I updated to Meteor v1.0.4, I was using v1.0.3 and the code worked perfectly. After updating though, I received the following error message on my server:

```
I20150318-02:39:58.808(-4)? Exception while invoking method 'addPost' TypeError: Object [object Object] has no method '_getCollection'
I20150318-02:39:58.809(-4)?     at getRawMongoCollection (packages/mrt:mongo-counter/counter.coffee:3:58)
I20150318-02:39:58.810(-4)?     at getCounterCollection (packages/mrt:mongo-counter/counter.coffee:9:3)
I20150318-02:39:58.810(-4)?     at callCounter (packages/mrt:mongo-counter/counter.coffee:13:14)
I20150318-02:39:58.810(-4)?     at _incrementCounter (packages/mrt:mongo-counter/counter.coffee:27:12)
I20150318-02:39:58.810(-4)?     at [object Object].Meteor.methods.addPost (app/server/server.js:4:39)
I20150318-02:39:58.810(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150318-02:39:58.810(-4)?     at packages/ddp/livedata_server.js:648:1
I20150318-02:39:58.811(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150318-02:39:58.811(-4)?     at packages/ddp/livedata_server.js:647:1
I20150318-02:39:58.811(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

```

I don't have a lot of experience with Meteor or node.js. (I'm not sure if I'm even sure if this error message is enough to fix the problem.) Regardless, do you know what may be the reason `incrementCounter ` doesn't work on v1.0.4, and could it be fixed? I had to downgrade back to v1.0.3 to get my app to work again.

Thanks

**Comment by mariorodriguespt** [comment]
+1

**Comment by mariorodriguespt** [comment]
https://github.com/awwx/meteor-mongo-counter/pull/4

**Comment by Manto** [comment]
Use https://atmospherejs.com/osv/mongo-counter
